spring:
  datasource:
    url: jdbc:sqlite:/Users/LinhDT/tunk/vtask.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
